table DuckData
	lineageTag: 967938bc-37ac-43ed-acd4-f9ce5d8fd5f0

	measure Measure = Khariton.Convert.DayHourMinute(32400,9)
		lineageTag: 85ba2420-d7ae-47d1-8f5b-5e53f94ca695

	column Duck
		dataType: string
		lineageTag: 27fe14da-daf8-4f73-b611-a8a750c4b24c
		summarizeBy: none
		sourceColumn: Duck

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 943b1941-cca7-4813-9cd6-6b8eb9fa3caa
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Purchase_Method
		dataType: string
		lineageTag: dc228460-5dc0-4622-9591-fb510f8e8a31
		summarizeBy: none
		sourceColumn: Purchase_Method

		annotation SummarizationSetBy = Automatic

	column Purchase_Retailer
		dataType: string
		lineageTag: 0de8b2e9-3c86-4aef-923b-3a2983540bdb
		summarizeBy: none
		sourceColumn: Purchase_Retailer

		annotation SummarizationSetBy = Automatic

	column Purchase_City
		dataType: string
		lineageTag: 95afceec-63f8-45b5-bc2a-4fc018084d45
		summarizeBy: none
		sourceColumn: Purchase_City

		annotation SummarizationSetBy = Automatic

	column Purchase_State
		dataType: string
		lineageTag: 286edfda-e929-4239-8da2-8765f950838d
		summarizeBy: none
		sourceColumn: Purchase_State

		annotation SummarizationSetBy = Automatic

	column Purchase_Country
		dataType: string
		lineageTag: ec4f8510-50df-4ac0-99e9-9209151ebd8f
		summarizeBy: none
		sourceColumn: Purchase_Country

		annotation SummarizationSetBy = Automatic

	column ISO_Code
		dataType: string
		lineageTag: 8bd8ebf0-a77a-422c-ada3-1a954a1c9f0e
		summarizeBy: none
		sourceColumn: ISO_Code

		annotation SummarizationSetBy = Automatic

	column Date_Bought
		dataType: dateTime
		formatString: mm/dd/yy
		lineageTag: ed489913-d002-423d-b090-592a54da0156
		summarizeBy: none
		sourceColumn: Date_Bought

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Latitude
		dataType: double
		lineageTag: dea1fd0a-be1b-44b6-b33c-114d22557a61
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: 1784bb20-f82d-4c72-8160-eae1bec7f775
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'About Me'
		dataType: string
		lineageTag: 55b4a01f-5c60-45c8-83ad-e10a3a1b3100
		summarizeBy: none
		sourceColumn: About Me

		annotation SummarizationSetBy = Automatic

	column Buyer
		dataType: string
		lineageTag: dedb75ba-0f54-433c-ad1d-34848f7c41a8
		summarizeBy: none
		sourceColumn: Buyer

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 18275f8b-4403-4607-92ff-eecc3c4aee7a
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Total_Weight
		dataType: double
		lineageTag: 217a87d2-6df6-4613-b801-c7fd716dd58d
		summarizeBy: sum
		sourceColumn: Total_Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Height
		dataType: double
		lineageTag: 0608df18-8f5c-42c9-b9a0-95a9f18b3cd3
		summarizeBy: sum
		sourceColumn: Height

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Width
		dataType: double
		lineageTag: b3a8a15b-9d64-41b0-b15a-21752c8f6421
		summarizeBy: sum
		sourceColumn: Width

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Length
		dataType: double
		lineageTag: dd604b6a-c701-4d45-a66c-4e8736b7f0da
		summarizeBy: sum
		sourceColumn: Length

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Avg Weight'
		dataType: string
		lineageTag: 25625667-f9d4-4d6f-a40d-319ba7989876
		summarizeBy: none
		sourceColumn: Avg Weight

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: ed7a425c-0432-46c5-8432-cae361007200
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column image
		dataType: string
		lineageTag: 8ebde27d-d2fc-4026-93ba-f7c389aed67f
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: image

		annotation SummarizationSetBy = Automatic

	column Dimensions
		dataType: string
		lineageTag: e9b9ed60-66f6-4398-9dfc-dc3a6ca0f001
		summarizeBy: none
		sourceColumn: Dimensions

		annotation SummarizationSetBy = Automatic

	partition DuckData = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\allan\Documents\DS_Projects\Analyducks\Power BI V2\Data\DuckDataBI.xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"Duck", type text}, {"Name", type any}, {"Purchase_Method", type text}, {"Purchase_Retailer", type text}, {"Purchase_City", type text}, {"Purchase_State", type text}, {"Purchase_Country", type text}, {"ISO_Code", type text}, {"Date_Bought", type date}, {"Latitude", type number}, {"Longitude", type number}, {"About Me", type any}, {"Buyer", type text}, {"Quantity", Int64.Type}, {"Total_Weight", type number}, {"Height", type number}, {"Width", type number}, {"Length", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Avg Weight", each Number.RoundDown([Total_Weight]/[Quantity])),
				    #"Added Index" = Table.AddIndexColumn(#"Added Custom", "Index", 1, 1, Int64.Type),
				    #"Added Custom1" = Table.AddColumn(#"Added Index", "image", each "https://wallpaperaccess.com/full/4723250.jpg"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom1",{{"image", type text}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type1", "Dimensions", each Number.ToText(Number.Round([Length],1))&" x "&Number.ToText(Number.Round([Width],1))&" x "&Number.ToText(Number.Round([Height],1))&"cm || "&Number.ToText(Number.Round([Total_Weight],1))&"g "),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom2",{{"Dimensions", type text}})
				in
				    #"Changed Type2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

