table DuckData2
	lineageTag: 2b9f4e6d-9fe1-4695-ba5a-67c25453af94

	column Duck
		dataType: string
		lineageTag: a4cabd0b-83bf-4313-b4ad-6242a6a6e86b
		summarizeBy: none
		sourceColumn: Duck

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: b261b9a7-ab7d-4876-bcde-f9bf67d7d0c8
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Purchase_Method
		dataType: string
		lineageTag: b05001c6-eb73-45d3-9b9f-91df139dd63c
		summarizeBy: none
		sourceColumn: Purchase_Method

		annotation SummarizationSetBy = Automatic

	column Purchase_Retailer
		dataType: string
		lineageTag: 026c09bf-cdd3-465e-8d1f-5085781cd699
		summarizeBy: none
		sourceColumn: Purchase_Retailer

		annotation SummarizationSetBy = Automatic

	column Purchase_City
		dataType: string
		lineageTag: 243e5c7d-9961-4f8d-b34f-ea51ad1a29b4
		summarizeBy: none
		sourceColumn: Purchase_City

		annotation SummarizationSetBy = Automatic

	column Purchase_State
		dataType: string
		lineageTag: aef0b813-f6fb-44f5-99a9-43c90210ed32
		summarizeBy: none
		sourceColumn: Purchase_State

		annotation SummarizationSetBy = Automatic

	column Purchase_Country
		dataType: string
		lineageTag: 7b1d30f2-7a4f-4a57-b2c6-891da1a106df
		summarizeBy: none
		sourceColumn: Purchase_Country

		annotation SummarizationSetBy = Automatic

	column ISO_Code
		dataType: string
		lineageTag: 7c0184a1-e575-4563-b791-bc92707959d3
		summarizeBy: none
		sourceColumn: ISO_Code

		annotation SummarizationSetBy = Automatic

	column Date_Bought
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9af7687b-d399-4a73-9837-6b59e852dc2b
		summarizeBy: none
		sourceColumn: Date_Bought

		variation Variation
			isDefault
			relationship: ea115ee0-0003-4371-ba06-656666393e8a
			defaultHierarchy: LocalDateTable_50576dc1-7d6a-4abe-9499-75105a145c18.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Latitude
		dataType: double
		lineageTag: b5f177ba-2f98-4df0-85f2-80aff1d6ff83
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: 726919a0-6c56-46a3-870c-3c778d471358
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'About Me'
		dataType: string
		lineageTag: 83fe3b82-4c31-4e93-9e22-44ddab8ad53e
		summarizeBy: none
		sourceColumn: About Me

		annotation SummarizationSetBy = Automatic

	column Buyer
		dataType: string
		lineageTag: c2dc5af9-6774-43bf-87b8-fe5e262c67b9
		summarizeBy: none
		sourceColumn: Buyer

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: bd45fd15-fd3a-4faf-a857-54eb9230827e
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Total_Weight
		dataType: double
		lineageTag: 8b54b227-85bf-4c30-812b-73f93608f547
		summarizeBy: sum
		sourceColumn: Total_Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Height
		dataType: double
		lineageTag: 0be8676a-17bc-41ff-b928-1270427f0a50
		summarizeBy: sum
		sourceColumn: Height

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Width
		dataType: double
		lineageTag: fc87624c-6217-4e35-9f42-3f7b42a484f6
		summarizeBy: sum
		sourceColumn: Width

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Length
		dataType: double
		lineageTag: 0cdbf249-654f-405b-9b78-af4a8597339b
		summarizeBy: sum
		sourceColumn: Length

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Image
		dataType: string
		lineageTag: 423afb62-8a0b-4991-a802-8fd3ee364dda
		summarizeBy: none
		sourceColumn: Image

		annotation SummarizationSetBy = Automatic

	column 'Avg Weight'
		dataType: double
		lineageTag: 75e661f0-02b1-4f8c-99cf-f49fb0d733e5
		summarizeBy: sum
		sourceColumn: Avg Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 31e0b3e8-e24d-43de-97c1-4147b379ab76
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column 'image 2'
		dataType: string
		lineageTag: 97c7a171-40f1-457f-9395-e62870bc48a3
		summarizeBy: none
		sourceColumn: image

		annotation SummarizationSetBy = Automatic

	column Dimensions
		dataType: string
		lineageTag: bc6b4ffa-f532-4cbd-b490-258c2e9ddac4
		summarizeBy: none
		sourceColumn: Dimensions

		annotation SummarizationSetBy = Automatic

	partition DuckData2 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://rubberduckanalytics.sharepoint.com/Shared%20Documents/Data/DuckDataBI.xlsx"), null, true),
				    Table1_Table = Source{[Item="Table1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table1_Table,{{"Duck", type text}, {"Name", type any}, {"Purchase_Method", type text}, {"Purchase_Retailer", type text}, {"Purchase_City", type text}, {"Purchase_State", type text}, {"Purchase_Country", type text}, {"ISO_Code", type text}, {"Date_Bought", type date}, {"Latitude", type number}, {"Longitude", type number}, {"About Me", type any}, {"Buyer", type text}, {"Quantity", Int64.Type}, {"Total_Weight", type number}, {"Height", type number}, {"Width", type number}, {"Length", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Avg Weight", each Number.RoundDown([Total_Weight]/[Quantity])),
				    #"Added Index" = Table.AddIndexColumn(#"Added Custom", "Index", 1, 1, Int64.Type),
				    #"Added Custom1" = Table.AddColumn(#"Added Index", "image", each "https://wallpaperaccess.com/full/4723250.jpg"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom1",{{"image", type text}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type1", "Dimensions", each Number.ToText(Number.Round([Length],1))&" x "&Number.ToText(Number.Round([Width],1))&" x "&Number.ToText(Number.Round([Height],1))&"cm || "&Number.ToText(Number.Round([Total_Weight],1))&"g "),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom2",{{"Dimensions", type text}, {"Avg Weight", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type2", each Date.IsInCurrentYear([Date_Bought]))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

